defaults:
  - hydra: default
  # - logger: mlflow
  - _self_


seed: ${random_seed:}

metadata:
  tiling:
    tile_extent: 512
    stride: 256
    tissue_threshold: 0.5
    mpp: 0.5
  relative_path_prefix: /mnt/data/Projects/Lymph_nodes/MMCI/Immunohistochemistry
  tissue_mask_dest: data/tissue_masks
  annotation_mask_dest: data/annotation_masks
  cytokeratin_mask_dest: data/cytokeratin_masks
  ignore_mask_dest: data/ignore_masks
  cytokeratin_masks_path: mlflow-artifacts:/68/42ff2d1b9b8649bd94a4fe6360db201e/artifacts/cytokeratin_masks

  experiment_name: Lymph Nodes
  experiment_description: DAB data - masks + datasets
  run_name: DAB masks + datasets
  mlflow_uri: http://mlflow.rationai-mlflow:5000