defaults:
  - hydra: default
  # - logger: mlflow
  - _self_


seed: ${random_seed:}

metadata:
  tiling:
    min_roi_area: 0.75
    tile_crop: 224
    stride: 112 # 224 / 2
    tissue_threshold: 0.5
    mpp: 0.5
  relative_path_prefix: /mnt/data/Projects/lymph_nodes
  tissue_mask_dest: data/tissue_masks
  annotation_mask_dest: data/annotation_masks
  cytokeratin_mask_dest: data/cytokeratin_masks
  ignore_mask_dest: data/ignore_masks
  cytokeratin_masks_path: mlflow-artifacts:/68/42ff2d1b9b8649bd94a4fe6360db201e/artifacts/cytokeratin_masks
  color_separation_mask_dest: data/color_separation_masks

  experiment_name: Lymph Nodes
  experiment_description: DAB datasets ROI ${metada.tiling.tile_crop}
  run_name: DAB datasets
  mlflow_uri: http://mlflow.rationai-mlflow:5000