defaults:
  - _slide_paths/sources:
    - /datasets/infer/negative_lymph_nodes
    - /datasets/infer/positive_lymph_nodes
    - /datasets/test/positive_lymph_nodes
    - /datasets/test/negative_lymph_nodes
    - /datasets/train/tmas
    - /datasets/train/negative_lymph_nodes
    - /datasets/train/tmas
    - /datasets/val/negative_lymph_nodes
    - /datasets/val/tmas
  - _self_

__target__: prepro.tissue_masks.generate_tissue_masks
slide_paths:
  - __target__: prepro.data_source.ChainedDataSources

mpp: 2
reference_path: ${metadata.relative_path_prefix}
dest: ${metadata.tissue_mask_dest}
