[project]
name = "lymph-nodes"
version = "0.1.0"
authors = [
    { name = "Jakub Pekár", email = "jakubpekar@mail.muni.cz" },
    { name = "Tomáš Homola", email = "567740@mail.muni.cz" },
]
requires-python = ">=3.12,<3.14"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "lightning>=2.5.6",
    "mlflow<3.0.0",
    "rationai-masks",
    "rationai-mlkit",
    "torch>=2.9.0",
    "torchmetrics>=1.8.2",
]

[optional-dependencies]
dev = ["mypy", "ruff"]

[tool.uv.sources]
rationai-masks = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git" }
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git", rev = "feature/uv-lock" }
