[project]
name = "lymph-nodes"
version = "0.1.0"
authors = [
    { name = "Jakub Pekár", email = "jakubpekar@mail.muni.cz" },
    { name = "Tomáš Homola", email = "567740@mail.muni.cz" },
]
requires-python = ">=3.11,<3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "lightning>=2.5.5",
    "numpy>=2.3.4",
    "openslide-python>=1.4.2",
    "pandas>=2.3.3",
    "pyvips>=3.0.0",
    "rationai-masks",
    "rationai-mlkit",
    "rationai-tiling",
    "report",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]

[project.optional-dependencies]
dev = ["mypy", "pre-commit", "ruff"]


[tool.uv.sources]
report = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/tools/report.git" }
rationai-tiling = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/tiling.git", rev = "feature/uv-manager" }
rationai-masks = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/masks.git", rev = "feature/modular-tissue-mask" }
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git", rev = "feature/batch-sampler-new" }


[tool.pdm.scripts]
l = { composite = ["lint", "format", "mypy"] }
lint = "ruff check --fix"
format = "ruff format"
mypy = "mypy ."
post_install = { composite = [
    "pre-commit autoupdate",
    "pre-commit install",
    "pre-commit install --hook-type commit-msg",
] }

[tool.pdm]
distribution = false
