# @package _global_

seed: 42
slides_uri: ???    # e.g. runs:/<run_id>/slides.csv
patients_uri: ???  # e.g. runs:/<run_id>/patients.csv

splits: {}

metadata:
  run_name: "✂️ Split · ${dataset.name}"
  description: Dataset split for ${dataset.name}
  hyperparams:
    seed: ${seed}
    name: ${dataset.name}
