# @package _global_

max_workers: 4

metadata:
  run_name: Patient Dataset of ${dataset.name}
  description: Data exploration & Patient Dataset of ${dataset.name}
  hyperparams:
    institute: ${dataset.institute}
    name: ${dataset.name}
