# @package _global_

defaults:
  - base
  - /experiment:
  - _self_

request_limit: 4
request_timeout: 18000
report_request_timeout: 24000
num_repeats: 5
url: "http://rayservice-qc-serve-svc.rationai-jobs-ns.svc.cluster.local:8000/"
mask_level: 3
sample_level: 1
output_path: ${lymph_nodes_artifacts}/qc_masks/${data_name}

metadata:
  run_name: QC Masks ${data_name}
  description: Quality control masks for ${data_name}
