# @package _global_

defaults:
  - base
  - _self_


metadata:
  run_name: Slide Dataset ${dataset.name}
  description: Slide Dataset for ${dataset.institute}
  hyperparams:
    institute: ${dataset.institute}
    name: ${dataset.name}