# @package _global_

defaults:
  - base
  - _self_


mpp: 0.5
tile_extent: 224
stride: 112


min_tissue_coverage: 0
max_blur_coverage: 0

metadata:
  run_name: Tiling ${dataset.name}
  description: Tile extraction for ${dataset.name} at ${mpp} mpp, tile extent ${tile_extent}, stride ${stride}
  hyperparams:
    mask_level: ${mask_level}
    sample_level: ${sample_level}
