# @package _global_

mpp: 0.5
tile_extent: 224
stride: 224
rows_per_shard: 100_000

slides_uri: ???
pipeline: ???


metadata:
  run_name: Tiling ${dataset.name}
  description: Tile extraction and embedding for ${dataset.name}
  hyperparams:
    mpp: ${mpp}
    tile_extent: ${tile_extent}
    stride: ${stride}
    rows_per_shard: ${rows_per_shard}
    name: ${dataset.name}
