# @package _global_

defaults:
  - base
  - _self_

mpp: 4.0
max_concurrent: 50
artifact_path: tissue_masks

metadata:
  run_name: Tissue Masks ${dataset.name}
  description: Tissue masks for ${dataset.name} at ${mpp} mpp
