_target_: lymph_nodes.modeling.ClsNet
backbone:
  _target_: lymph_nodes.modeling.encoder.VGG16
bottleneck:
  _target_: torch.nn.AdaptiveAvgPool2d
  output_size: [7, 7]
head:
  _target_: lymph_nodes.modeling.blocks.BinaryClassifier
  features: [25088, 4096, 4096, 1]