defaults:
  - _self_
  - hydra: default
  - save: local

reporter:
  title: "SNB IHC Case 1 Slide 3 - Local Test"

  save:
    _target_: report.save.LocalReportStorer
    output_path: report_SNB_IHC_CASE_1_SLIDE_3-1.html

  background:
    _target_: report.masks.SlideRetriever
    paths:
      - /mnt/data/MOU/lymph_nodes/dataset1-ihc-2023/SNB_IHC_CASE_1_SLIDE_3-1.mrxs
    layer_name: background

  mask_retrievers:
    - _target_: report.masks.ArtifactURIMasksRetriever
      artifact_uri: "mlflow-artifacts:/4/21a5ba38c280421885b4508a75495069/artifacts/heatmaps"
      layer_name: Classification Heatmap
      shader_conf:
        type: "heatmap"
        modifiable: true
        color: "#FF0000"
        opacity: 0.5
        visible: true

    # - _target_: report.masks.ArtifactURIMasksRetriever
    #   artifact_uri: "mlflow-artifacts:/68/b45545c7d74f47d19620b584b3cd1cf1/artifacts/tissue_masks"
    #   layer_name: Tissue Mask
    #   shader_conf:
    #     type: "heatmap"
    #     modifiable: true
    #     color: "#00FF00"
    #     opacity: 0.3
    #     visible: true
