defaults:
  - hydra: default
  - _self_


seed: ${random_seed:}

metadata:
  slides: mlflow-artifacts:/68/04f3267cd2fc4c6bbecbacb3336a13a1/artifacts/Inference/slides.parquet
  predictions: mlflow-artifacts:/68/d3bb2554870f4bd1a3f783def5ff7d96/artifacts/predictions.parquet
  heatmap_dest: "./data/heatmpas"

  experiment_name: Lymph Nodes
  experiment_description: DAB test heatmaps for run d3bb2554870f4bd1a3f783def5ff7d96
  run_name: DAB test heatmaps
  mlflow_uri: http://mlflow.rationai-mlflow:5000
  # mlflow_uri: https://mlflow.rationai.cloud.trusted.e-infra.cz