defaults:
  - _self_
  - hydra: default
  - logger: mlflow
  - /model@model.model: ???

seed: ${random_seed:}
mode: [fit, test]

checkpoint:
  test: best

trainer:
  max_epochs: 25
  log_every_n_steps: 100
  enable_checkpointing: true
  gradient_clip_val: 0.1
  callbacks:
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      save_last: true
      auto_insert_metric_name: true
      monitor: validation/loss
      mode: min
    # early_stopping:
    #   _target_: lightning.pytorch.callbacks.EarlyStopping
    #   monitor: validation/loss
    #   mode: min
    #   patience: 10
    # cls_mask_builder:
    #   _target_: lymph_nodes.callbacks.ClsMaskBuilder
    #   artifact_path: classifcation_heatmaps
    finetuning:
      _target_: lightning.pytorch.callbacks.BackboneFinetuning
      unfreeze_backbone_at_epoch: 30

metadata:
  experiment_name: Lymph Nodes

data:
  _target_: lymph_nodes.data.DataModule
  epoch_size: 1000
  num_workers: 12
  batch_distribution: [0.5, 0.05, 0.45]

tuner: {}
# dynamic_batch_size: True
