defaults:
  - _self_
  - hydra: default
  - logger: mlflow
  # - /data/datasets@data.train: ${task}/${kind}/train
  # - /data/datasets@data.val: ${task}/${kind}/val
  # - /data/datasets@data.test: ${task}/test
  # - /data/datasets@data.predict: ${task}/predict
  - /model/backbone: ???
  
seed: ${random_seed:}
mode: ???
task: ???
kind: ???
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 100
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 3
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min
      patience: 10

data:
  batch_size: 16
  epoch_size: 500
  positive_batch_split: 0.5
  num_workers: 10

metadata:
  experiment_name: Lymph Nodes
  run_name: "DAB ${mode} | Backbone: ${model.backbone} | Task: ${task} | Dataset: ${kind}"
  description: >
    Running a ${mode} mode deep learning model on the Lymph Nodes DAB dataset.
    This experiment is configured for the ${task} task using the ${kind} dataset and 
    the ${model.backbone} backbone architecture.
  hyperparams: {}
