defaults:
  - _self_
  - hydra: default
  - logger: mlflow
  - /model/backbone: ???
  
seed: ${random_seed:}
mode: ???
task: ???
kind: ???
checkpoint: null

trainer:
  enable_checkpointing: True
  max_epochs: 100
  log_every_n_steps: 5
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 3
      monitor: validation/loss
      mode: min
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: validation/loss
      mode: min
      patience: 10
    # Predict callbacks
    - _target_: lymph_nodes.callbacks.tile_mask_builder.TileMaskBuilderTest



data:
  batch_size: 64
  epoch_size: 1000
  positive_batch_split: 0.5
  num_workers: 8

metadata:
  experiment_name: Lymph Nodes
  run_name: "DAB ${mode} | Backbone: ${model.backbone} | Task: ${task} | Dataset: ${kind}"
  description: >
    Running a ${mode} mode deep learning model on the Lymph Nodes DAB dataset.
    This experiment is configured for the ${task} task using the ${kind} dataset and 
    the ${model.backbone} backbone architecture.
  hyperparams: {}
