defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.predict: tile_embeddings/tile_embeddings
  - /data/embeddings/uris
  - _self_

seed: 42
mode: predict
checkpoint: ???
foundation: prov-gigapath
level: ???

embeddings_uri: ${uris.embeddings.${key:${foundation}}.${level}}

trainer: {}

data:
  batch_size: 1
  num_workers: 4

model:
  _target_: lymph_nodes.attention_mil_lymph_nodes.LymphNodesMIL
  foundation: ${foundation}

metadata:
  experiment_name: 'Lymph Nodes'
  run_name: '🔮 Predict: ${foundation} ${level}'
  description: 'MIL Predict for Lymph Node Metastasis'
  hyperparams:
    foundation: ${foundation}
    level: ${level}
