defaults:
  - hydra: default
  - logger: mlflow
  - /data/datasets@data.train: tile_embeddings/tile_embeddings
  - /data/embeddings/uris
  - _self_

seed: 42
mode: fit
checkpoint: null
foundation: ???

embeddings_uri: ${uris.embeddings.${key:${foundation}}}

trainer:
  enable_checkpointing: True
  max_epochs: 50
  log_every_n_steps: 3
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      save_top_k: 1
      monitor: val/AUC
      mode: max
    - _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val/loss
      mode: min
      patience: 10

data:
  batch_size: 1
  num_workers: 4
  kfold_splits: 5
  k: 1

model:
  _target_: lymph_nodes.attention_mil_lymph_nodes.LymphNodesMIL
  lr: 0.0001
  pos_weight: 1.0
  foundation: ${foundation}

metadata:
  experiment_name: 'Lymph Node Metastasis'
  run_name: '🏋️‍♂️ Training: ${foundation} (fold ${data.k}/${data.kfold_splits}) MIL'
  description: 'MIL for Lymph Node Metastasis Detection'
  hyperparams: {}
