defaults:
  - _sources[0].slides: deatasets/infer/negative_lymph_nodes
  - sources[1].slides: datasets/infer/positive_lymph_nodes
  - _self_


__target__: prepro.tiling.tile_dataset
sources:
  - slides: ...
    source_kind: lymph_node
    slide_metastazis: False
    desired_mpp: ${metadata.tiling.mpp}
    tissue_threshold: ${metadata.tiling.tissue_threshold}
    tile_extent: ${metadata.tiling.tile_extent}
    stride: ${metadata.tiling.stride}
    tissue_masks_dir: ${metadata.tissue_mask_dest}
    annotation_masks_dir: ${metadata.annotation_mask_dest}
    realtive_path_prefix: ${metadata.relative_path_prefix}
  
  - slides: ...
    source_kind: lymph_node
    slide_metastazis: True
    tdesired_mpp: ${metadata.tiling.mpp}
    tissue_threshold: ${metadata.tiling.tissue_threshold}
    tile_extent: ${metadata.tiling.tile_extent}
    stride: ${metadata.tiling.stride}
    tissue_masks_dir: ${metadata.tissue_mask_dest}
    annotation_masks_dir: ${metadata.annotation_mask_dest}
    realtive_path_prefix: ${metadata.relative_path_prefix}

dataset_name: Inference 
